# Generated by Django 5.1.1 on 2024-09-28 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Running', 'Running'), ('Cycling', 'Cycling'), ('Weightlifting', 'Weightlifting'), ('Swimming', 'Swimming'), ('Hiking', 'Hiking'), ('Yoga', 'Yoga'), ('Climbing', 'Climbing'), ('Calisthenics', 'Calisthenics'), ('Resistance Training', 'Resistance Training'), ('Other', 'Other')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.PositiveIntegerField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('calories_burned', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
